# -*- coding: utf-8 -*-
"""Generative_Text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qsb1O4ZUf_aBPgAPkj4IYZNc8wWRP2qY
"""

!pip install -q gradio
!pip install datasets

!pip install -q git+https://github.com/huggingface/transformers.git

import gradio as gr
import tensorflow as tf
from transformers import TFGPT2LMHeadModel,GPT2Tokenizer
tokenizer=GPT2Tokenizer.from_pretrained("gpt2")
model=TFGPT2LMHeadModel.from_pretrained("gpt2",pad_token_id=tokenizer.eos_token_id)

def generator_text(inputs):
  input_id=tokenizer.encode(inputs,return_tensors='tf')
  beam_output=model.generate(input_id,max_length=100,num_beams=5,no_repeat_ngram_size=2,early_stopping=True)
  output=tokenizer.decode(beam_output[0],skip_special_tokens=True,clean_up_tokenization_spaces=True)
  return ".".join(output.split(".")[:-1]) + "."

output_text=gr.Textbox()
gr.Interface(fn=generator_text,outputs=output_text,inputs="textbox",title="Sentence_Generator(GPT-2)").launch()